### ISSUE TITLE
How to add only first federal/state exemptions to PDF and the rest to addendum

### ISSUE THREAD

**Issue by miabonardi** [miabonardi/docassemble-FinancialStatementShortForm#20]
![Screen Shot 2024-01-23 at 1 57 26 PM](https://github.com/miabonardi/docassemble-FinancialStatementShortForm/assets/65858862/9d078b53-fae0-4b7c-a147-ac6b7a74700c)

Currently looks like this in attachment block: 
```      
- "exemptions_federal_income_tax": |
          ${ comma_and_list(federal_tax_exemptions.true_values()) }
- "exemptions_state_income_tax": |
          ${ comma_and_list(state_tax_exemptions.true_values()) }
```

**Comment by plocket** [comment]
If I understand the need correctly, it's about using the indexes for lists. `.true_values()` gets you a regular list, so you can get items from it just like any other python list. Adding only the first:
```
- "exemptions_federal_income_tax": |
          ${ federal_tax_exemptions.true_values()[0] }
- "exemptions_state_income_tax": |
          ${ state_tax_exemptions.true_values()[0] }
```

For getting the rest, you can use python [list slicing](https://docs.python.org/3/tutorial/introduction.html#lists):

```python
state_tax_exemptions.true_values()[1:]
```

The index number before the `:` includes the item at that index. Just so you know, the index number after the `:` excludes the item at _that_ index.

**Comment by miabonardi** [comment]
@plocket Thanks so much! This was what I needed.
