### ISSUE TITLE
When someone is self-employed, they shouldn't be asked to look at their paystub for job information

### ISSUE THREAD

**Issue by nonprofittechy** [miabonardi/docassemble-FinancialStatementShortForm#32]
![image](https://github.com/LemmaLegalConsulting/docassemble-FinancialStatementShortForm/assets/7645641/34c2bb28-049a-43f1-b57a-e11ad7b0cee4)

**Comment by nonprofittechy** [comment]
And we should skip the follow-up paystub questions (or I guess make them optional. At least they are going to be uncommon in a self-employed scenario)

![image](https://github.com/LemmaLegalConsulting/docassemble-FinancialStatementShortForm/assets/7645641/96c54caf-89d2-401e-a64e-46451384098d)

**Comment by miabonardi** [comment]
Completed
