### ISSUE TITLE
Make currency symbol show in interview but not in doc

### ISSUE THREAD

**Issue by miabonardi** [miabonardi/docassemble-FinancialStatementShortForm#8]
![Screen Shot 2024-01-12 at 10 04 59 AM](https://github.com/miabonardi/docassemble-FinancialStatementShortForm/assets/65858862/c87193d9-e882-4f39-9ff9-da6d6632fad8)

**Comment by miabonardi** [comment]
```
initial: True
code: |
  set_locale(currency_symbol=' ')
```
---

**Comment by miabonardi** [comment]
@plocket setting `set_locale(currency_symbol=' ')` like this removes the $ throughout the interview. Is there a way around this you know of? 

![Screen Shot 2024-01-17 at 10 33 09 AM](https://github.com/miabonardi/docassemble-FinancialStatementShortForm/assets/65858862/f217c43d-78fe-49ab-9dbe-591a88be4de3)

**Comment by plocket** [comment]
For the People of the Future: of the solutions available, we decided to use the keyword argument `symbol=''` wherever we needed to avoid the currency symbol. It's more annoying to do initially, but in the long run it looks more robust and easier to maintain than trying to juggle global settings and deal with the complications that might cause.
